language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
install:
  - sudo apt-get install portaudio19-dev
  - pip install -r requirements.txt
  - pip install codecov
  - pip install nose-cov
  - python -c "import nltk; nltk.download('stopwords')"
script:
  - nosetests --nocapture --with-cov --cov-config .coveragerc
after_success:
  - codecov
